[features]
seeds = false
skip-lint = false

[programs.mainnet]
gimme_idea = "11111111111111111111111111111111" # placeholder; replace after deployment

[programs.devnet]
gimme_idea = "11111111111111111111111111111111" # placeholder; replace after deployment

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
